loader:
  dataset_path: 
    train: /cmnfs/data/proteomics/foundational_model/PretrainV1/parquets/*train*
    val: /cmnfs/data/proteomics/foundational_model/PretrainV1/parquets/*val*
    test: /cmnfs/data/proteomics/foundational_model/PretrainV1/parquets/*test*
  dictionary_path: /cmnfs/home/j.lapin/projects/foundational/save/notes/mkb_dictionary.txt
  pep_length: [0, 30]
  top_pks: 100
  buffer_size: 10000
  batch_size: 100
  num_workers: 12
  scratch:
    use: False
    path: /media/storage/scratch/pretrain/
