batch_size: 100
lr: 0.0001
lr_warmup: False
lr_warmup_start: 1.0e-6
lr_warmup_end: 1.0e-4
lr_warmup_steps: 20000
pretrain_path:
dswts: # Load weights from previous downstream run (project path->timestamp)
epochs: 30
steps_per_epoch: 10000
train_encoder: True
encoder_start: 0
log: True # write to downstream_only directory
save_weights: True
# Loader options
loader:
  dataset_path: 
    train: /cmnfs/data/proteomics/foundational_model/ninespecies_xy/parquets/instanovo*train*
    val: /cmnfs/data/proteomics/foundational_model/ninespecies_xy/parquets/instanovo*val*
    test: /cmnfs/data/proteomics/foundational_model/ninespecies_xy/parquets/instanovo*test*
    #train: /cmnfs/data/proteomics/foundational_model/MassiveKB/parquets/*train*
    #val: /cmnfs/data/proteomics/foundational_model/MassiveKB/parquets/instanovo_val.parquet
    #test: /cmnfs/data/proteomics/foundational_model/MassiveKB/parquets/*test*
  #dictionary_path: /cmnfs/home/j.lapin/projects/foundational/save/notes/mkb_dictionary.txt
  dictionary_path: /cmnfs/data/proteomics/foundational_model/ninespecies_xy/ninespecies_dictionary.txt
  pep_length: [0, 30]
  top_pks: 100
  buffer_size: 10000
  batch_size: 100
  num_workers: 4
  scratch:
    use: False
    path: /media/storage/scratch/ninespecies/
# Downstream task specific options
denovo_ar:
  head_dict:
    running_units: 512
    sequence_length: 30
    depth: 9
    d: 64
    h: 8
    ffn_multiplier: 1
    ce_units: 256
    use_charge: True
    use_energy: False
    use_mass: True
    prec_type: 'inject_pre' # inject_pre | inject_ffn | inject_norm | pretoken | posttoken | None
    norm_type: 'layer'
    prenorm: True
    preembed: True
    penultimate_units:
    pool: False
    dropout: 0.25
    alphabet: False
denovo_diff:
  head_dict:
    running_units: 512
    sequence_length: 30
    depth: 6
    d: 64
    h: 8
    ffn_multiplier: 4
    ce_units: 256
    use_charge: True
    use_energy: False
    use_mass: True
    prec_type: None
    norm_type: 'layer'
    prenorm: True
    preembed: True
    penultimate_units:
    pool: False
    dropout: 0
    alphabet: False
  self_condition: True

