seed:
max_peaks: 100
epochs: 1
steps_per_report: 10000
max_steps: 1e10
batch_size: 100
lr: 1e-4
tasks:
  #- trinary_mz
  #- trinary_ab
  #- hidden_mz
  #- hidden_ab
  #- hidden_spectrum
  #- hidden_charge
  #- hidden_mass
  #- maldi
  - resid_regr
downstream:
  #- denovo_ar

log_wandb: False
project: diffusion
load: False
loadpath: save/2024-03-23_18-49-24.152971/weights/
log: False
svwts: False
svfreq: 1800
svgrad: False
debug: False
header: "Diffusion w/ AR model hyperparameters (lr and dropout)"
