loader:
  dataset_path: 
    train: /cmnfs/data/proteomics/foundational_model/PretrainV1/parquets/*train*parquet
    val: /cmnfs/data/proteomics/foundational_model/PretrainV1/parquets/*val*parquet
    test: /cmnfs/data/proteomics/foundational_model/PretrainV1/parquets/*test*parquet
  dictionary_path: /cmnfs/home/j.lapin/projects/foundational/save/notes/mkb_dictionary.txt
  pep_length: [0, 30]
  top_pks: 100
  buffer_size: 10000
  batch_size: 100
  num_workers: 4
  remove_columns:
    - name # V1, MKB
    - sequence # V1, MKB
    #- method # V2
    #- instrument # V2
  val_steps: 100
  scratch:
    use: False
    path: /media/storage/scratch/pretrain/
